/**CREATE TABLE ASSESSMENT (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
	project VARCHAR(100),
	sub_contractor VARCHAR(100),
	contract_number VARCHAR(30),
	assessment_start_date VARCHAR(30),
	assessment_end_date VARCHAR(30),
	status VARCHAR(30),
	created_date VARCHAR(30),
	created_by VARCHAR(30),
	assigned_to VARCHAR(30),
	score_1 VARCHAR(3),
	score_2 VARCHAR(3),
	score_3 VARCHAR(3),
	score_4 VARCHAR(3),
	score_5 VARCHAR(3),
	score_6 VARCHAR(3),
	score_7 VARCHAR(3),
	score_8 VARCHAR(3),
	score_9 VARCHAR(3),
	score_10 VARCHAR(3),
	score_11 VARCHAR(3),
	score_12 VARCHAR(3),
	score_13 VARCHAR(3),
	score_14 VARCHAR(3),
);**/
--create SQL commit change
CREATE table ASSESSMENT_2 (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
	contract VARCHAR(100),
	assessment_date VARCHAR(30),
	floor VARCHAR(30),
	block_zone VARCHAR(30),
	location_flat VARCHAR(30),
	sub_factor_item VARCHAR(100),
	form_1_soundness VARCHAR(10),
	form_1_evenness VARCHAR(10),
	form_1_level VARCHAR(10),
	form_1_fall VARCHAR(10),
	form_2_soundness VARCHAR(10),
	form_2_evenness VARCHAR(10),
	form_2_level VARCHAR(10),
	form_2_fall VARCHAR(10),
	form_3_soundness VARCHAR(10),
	form_3_evenness VARCHAR(10),
	form_3_level VARCHAR(10),
	form_3_fall VARCHAR(10),
	form_4_soundness VARCHAR(10),
	form_4_evenness VARCHAR(10),
	form_4_level VARCHAR(10),
	form_4_fall VARCHAR(10),

	floor2 VARCHAR(30),
	block_zone2 VARCHAR(30),
	location_flat2 VARCHAR(30),
	sub_factor_item2 VARCHAR(100),
	floor3 VARCHAR(30),
	block_zone3 VARCHAR(30),
	location_flat3 VARCHAR(30),
	sub_factor_item3 VARCHAR(100),
	floor4 VARCHAR(30),
	block_zone4 VARCHAR(30),
	location_flat4 VARCHAR(30),
	sub_factor_item4 VARCHAR(100),
	floor5 VARCHAR(30),
	block_zone5 VARCHAR(30),
	location_flat5 VARCHAR(30),
	sub_factor_item5 VARCHAR(100),
	form_t21_evenness VARCHAR(10),
	form_t21_level VARCHAR(10),
	form_t21_fall VARCHAR(10),
	form_t22_evenness VARCHAR(10),
	form_t22_level VARCHAR(10),
	form_t22_fall VARCHAR(10),
	form_t23_evenness VARCHAR(10),
	form_t23_level VARCHAR(10),
	form_t23_fall VARCHAR(10),
	form_t24_evenness VARCHAR(10),
	form_t24_level VARCHAR(10),
	form_t24_fall VARCHAR(10),
	form_t31_soundness VARCHAR(10),
	form_t32_soundness VARCHAR(10),
	form_t33_soundness VARCHAR(10),
	form_t34_soundness VARCHAR(10),
	form_t41_lintol VARCHAR(10),
	form_t41_evenness VARCHAR(10),
	form_t41_jointwidth VARCHAR(10),
	form_t41_finish VARCHAR(10),
	form_t42_lintol VARCHAR(10),
	form_t42_evenness VARCHAR(10),
	form_t42_jointwidth VARCHAR(10),
	form_t42_finish VARCHAR(10),
	form_t43_lintol VARCHAR(10),
	form_t43_evenness VARCHAR(10),
	form_t43_jointwidth VARCHAR(10),
	form_t43_finish VARCHAR(10),
	form_t44_lintol VARCHAR(10),
	form_t44_evenness VARCHAR(10),
	form_t44_jointwidth VARCHAR(10),
	form_t44_finish VARCHAR(10),
	form_t51_evenness VARCHAR(10),
	form_t51_plumb VARCHAR(10),
	form_t51_soundness VARCHAR(10),
	form_t51_finish VARCHAR(10),
	form_t52_evenness VARCHAR(10),
	form_t52_plumb VARCHAR(10),
	form_t52_soundness VARCHAR(10),
	form_t52_finish VARCHAR(10),
	form_t53_evenness VARCHAR(10),
	form_t53_plumb VARCHAR(10),
	form_t53_soundness VARCHAR(10),
	form_t53_finish VARCHAR(10),
	form_t54_evenness VARCHAR(10),
	form_t54_plumb VARCHAR(10),
	form_t54_soundness VARCHAR(10),
	form_t54_finish VARCHAR(10),
	created_by VARCHAR(30),
	created_date VARCHAR(30),
	assigned_to VARCHAR(30),
	status VARCHAR(30),
	approved_by_prof VARCHAR(3),
	approved_by_chief VARCHAR(3),
	remarks VARCHAR(255),
	attachments VARCHAR(255)
);


CREATE  TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  username VARCHAR(45),
  password VARCHAR(45),
  enabled INTEGER
);

CREATE TABLE user_roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  username varchar(45),
  role varchar(45)
  );
  /**
CREATE  TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  username VARCHAR(45) NOT NULL ,
  password VARCHAR(45) NOT NULL ,
  enabled INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE user_roles (
  id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(45) NOT NULL,
  role varchar(45) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uni_username_role (role,username),
  KEY fk_username_idx (username),
  CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username)
  );**/

CREATE TABLE factors(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  factor_cd varchar(20),
  dscp varchar(50));

CREATE TABLE tables(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  factor_id integer,
  subfactor integer,
  dscp varchar(60)
  );

CREATE TABLE points(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  dscp varchar(50));

CREATE TABLE area(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  contract_id integer,
  table_id integer,
  block_zone varchar(50),
  floor varchar(20),
  location_flat varchar(100));

 CREATE TABLE contract(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  title varchar(200),
  contract_no varchar(20),
  contractor varchar(200),
  contract_start varchar(20),
  contract_end varchar(20));

CREATE TABLE assessment(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  area_id integer,
  points_id integer,
  spot1 varchar(5),
  spot2 varchar(5),
  spot3 varchar(5),
  spot4 varchar(5));

Create TABLE scores(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  cd varchar(5)
  );

