CREATE TABLE ASSESSMENT (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
	project VARCHAR(100),
	sub_contractor VARCHAR(100),
	contract_number VARCHAR(30),
	assessment_start_date VARCHAR(30),
	assessment_end_date VARCHAR(30),
	status VARCHAR(30),
	created_date VARCHAR(30),
	created_by VARCHAR(30),
	assigned_to VARCHAR(30),
	score_1 VARCHAR(3),
	score_2 VARCHAR(3),
	score_3 VARCHAR(3),
	score_4 VARCHAR(3),
	score_5 VARCHAR(3),
	score_6 VARCHAR(3),
	score_7 VARCHAR(3),
	score_8 VARCHAR(3),
	score_9 VARCHAR(3),
	score_10 VARCHAR(3),
	score_11 VARCHAR(3),
	score_12 VARCHAR(3),
	score_13 VARCHAR(3),
	score_14 VARCHAR(3),
);



CREATE  TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  username VARCHAR(45),
  password VARCHAR(45),
  enabled INTEGER
);

CREATE TABLE user_roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  username varchar(45),
  role varchar(45)
  );
  /**
CREATE  TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
  username VARCHAR(45) NOT NULL ,
  password VARCHAR(45) NOT NULL ,
  enabled INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE user_roles (
  id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(45) NOT NULL,
  role varchar(45) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uni_username_role (role,username),
  KEY fk_username_idx (username),
  CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username)
  );**/


