--INSERT INTO WORK (status, created_date, created_by) VALUES ('DRAFT', '12/04/2015', 'TEST USER');
--INSERT INTO WORK (status, created_date, created_by) VALUES ('SUBMITTED', '12/04/2015', 'TEST USER');
--INSERT INTO WORK (status, created_date, created_by) VALUES ('REJECTED', '12/04/2015', 'TEST USER');
--INSERT INTO WORK (status, created_date, created_by) VALUES ('RETURNED', '12/04/2015', 'TEST USER');
--INSERT INTO WORK (status, created_date, created_by) VALUES ('APPROVED', '12/04/2015', 'TEST USER');

--INSERT INTO ASSESSMENT (project, sub_contractor, contract_number, assessment_start_date, assessment_end_date, status, created_date, created_by, assigned_to, score_1, score_2, score_3, score_4, score_5, score_6, score_7, score_8, score_9, score_10, score_11, score_12, score_13, score_14) VALUES ('Lift Modernization for Mei Shan House', 'Hitachi Elevator Engineering CO (HK) LTD', '20139135', '12/07/2015', '12/08/2015', 'FOR ASSESSMENT', '12/07/2015', 'assessor@hkha.com', 'assessor@hkha.com', 'A','B','C','D','N','A','A','B','B','C','C','D','D','N');
--INSERT INTO ASSESSMENT (project, sub_contractor, contract_number, assessment_start_date, assessment_end_date, status, created_date, created_by, assigned_to, score_1, score_2, score_3, score_4, score_5, score_6, score_7, score_8, score_9, score_10, score_11, score_12, score_13, score_14) VALUES ('Maintenance of Lift Installation for Construction', 'KONE Elevator (HK) LTD', '20139136', '12/08/2015', '12/10/2015', 'FOR ASSESSMENT', '12/08/2015', 'assessor@hkha.com', 'assessor@hkha.com', 'A','B','C','D','N','A','A','B','B','C','C','D','D','N');
--INSERT INTO ASSESSMENT (project, sub_contractor, contract_number, assessment_start_date, assessment_end_date, status, created_date, created_by, assigned_to, score_1, score_2, score_3, score_4, score_5, score_6, score_7, score_8, score_9, score_10, score_11, score_12, score_13, score_14) VALUES ('Lift Modernization for Ting Lung House', 'OTIS ELEVATOR CO (HK) LTD', '20139137', '12/09/2015', '12/15/2015', 'FOR ASSESSMENT', '12/09/2015', 'assessor@hkha.com', 'assessor@hkha.com', 'A','B','C','D','N','A','A','B','B','C','C','D','D','N');

INSERT INTO ASSESSMENT_2 (contract, assessment_date, floor, block_zone, location_flat, sub_factor_item, created_by, created_date, assigned_to, status, approved_by_prof, approved_by_chief) VALUES ('Sample Contract Title', '12/12/2015', '4', '3', 'Test location', '1.1 Grano / Terrazo / Cement Sand Screed', 'assessor', '12/12/2015', '', 'FOR ASSESSMENT', 'N', 'N');

